import fs from 'node:fs';import path from 'node:path';
const root=process.argv[2];if(!root)throw Error('Pass private report root');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const records=[];
for(const tag of ['COSTIGAN','SIGNATURE','SCOTTMOORE','SATISH','SYNERGY','WOOSLEY']){
 const dir=path.join(root,tag);if(!fs.existsSync(path.join(dir,'summary.json')))continue;
 const inv=JSON.parse(fs.readFileSync(path.join(dir,'inventory.json'),'utf8'));const summary=JSON.parse(fs.readFileSync(path.join(dir,'summary.json'),'utf8'));const t=summary.totals;
 const filename=inv.account==='compass627'?'costigan-historical-pilot.html':'historical-pilot.html';
 records.push({tag,team:inv.team,filename,leads:t.leads,closed:t.closed||0,complete:t.leads-t.incomplete,status:inv.sourceConfirmationPending?'Source confirmation pending':inv.dateConfirmationPending?'Start date review':t.incomplete?'Collecting':'Collected',sourceStarts:inv.sourceStarts});
}
fs.writeFileSync(path.join(root,'review-index.json'),JSON.stringify({generatedAt:new Date().toISOString(),records},null,2));
fs.writeFileSync(path.join(root,'index.html'),`<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TRU · Historical review</title><style>body{margin:0;background:#eeece6;color:#27313a;font:15px/1.5 system-ui}header{background:#27313a;color:#fff;padding:18px 5vw}main{max-width:1100px;margin:auto;padding:40px 24px}h1{font:40px Georgia}p{color:#666c69}table{width:100%;border-collapse:collapse;background:#faf9f5}th,td{text-align:left;padding:18px;border-bottom:1px solid #d5d2c8}th{font-size:11px;text-transform:uppercase}a{color:#27313a;font-weight:600}small{display:block;color:#8b6b43}section{overflow:auto}</style><header>TRU HQ · Private review</header><main><h1>Historical performance, with receipts.</h1><p>Active roster today. Source-specific collection periods. Each report separates earned milestones from current stage and shows how every count was calculated.</p><section><table><thead><tr><th>Team</th><th>Leads</th><th>History coverage</th><th>Raw conversion</th><th>Status</th></tr></thead><tbody>${records.map(r=>`<tr><td><a href="${r.tag}/${r.filename}">${esc(r.team)} →</a><small>${Object.entries(r.sourceStarts||{}).map(([s,d])=>esc(s)+' from '+d).join('<br>')}</small></td><td>${r.leads}</td><td>${r.complete} / ${r.leads}</td><td>${r.leads?(100*r.closed/r.leads).toFixed(1)+'%':'—'}${r.complete<r.leads?' · partial':''}</td><td>${esc(r.status)}</td></tr>`).join('')}</tbody></table></section><p>Raw conversion = distinct closed leads ÷ cohort leads × 100. A two-year selection does not imply two years of available data. No production data or webhooks have been changed.</p></main></html>`);
console.log(path.resolve(root,'index.html'));
