const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const org='00000000-0000-4000-8000-000000000001',team='00000000-0000-4000-8000-000000000002',profile='00000000-0000-4000-8000-000000000003';
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create table orgs(id uuid primary key);create table teams(id uuid primary key,org_id uuid references orgs(id));create table agents(id uuid primary key,team_id uuid,org_id uuid,excluded boolean);insert into orgs values('${org}');insert into teams values('${team}','${org}');insert into agents values('${profile}','${team}','${org}',false);grant select on teams,agents to service_role;`);
await db.exec(`create table person_stage_log(org_id uuid,team_id uuid,fub_person_id bigint,stage text,changed_at timestamptz,stage_class text,date_source text,unique(team_id,fub_person_id,stage));grant select,insert,update on person_stage_log to service_role;`);
for(const file of ['20260912024754_truehq_history_provenance.sql','20260912032307_truehq_history_publication.sql','20260912040150_truehq_history_projection.sql'])await db.exec(await fs.readFile(new URL('../../supabase/migrations/'+file,import.meta.url),'utf8'));
await db.exec(`insert into history_accounts values(1,'${team}','${org}','example',now());set role service_role;`);
const job=(await db.query(`insert into history_jobs(account_id,from_at,cutoff,source_policy,census_complete,expected_people,unresolved_people) values(1,'2026-01-01T08:00:00Z','2026-09-12T03:00:00Z','truehq-exact-sources-2026-v1',true,1,0) returning id`)).rows[0].id;
const validate=()=>db.query('select history_validate_job($1)',[job]);
await assert.rejects(validate(),/overlap/);
await db.query(`update history_jobs set live_capture_from='2026-09-12T02:00:00Z',webhook_verified_at=now(),reconciliation_verified_at=now(),overlap_verified_at=now() where id=$1`,[job]);
await assert.rejects(validate(),/Census count/);
await db.query(`insert into history_job_people values($1,42,'Zillow','eligible')`,[job]);
await assert.rejects(validate(),/interval gaps/);
await db.query(`insert into history_receipts values(1,42,$1,now(),'Zillow','truehq-exact-sources-2026-v1','test','{}')`,['a'.repeat(64)]);
await db.query(`insert into history_coverage(job_id,person_id,from_at,through_at,content_hash,pagination_complete,state,captured_at,account_id) values($1,42,'2026-01-01T08:00:00Z','2026-09-12T03:00:00Z',$2,true,'validated',now(),1)`,[job,'a'.repeat(64)]);
await assert.rejects(validate(),/Profile dispositions/);
await db.query('update history_jobs set profile_dispositions=$1 where id=$2',[JSON.stringify([{id:profile,org_id:org,team_id:team,excluded:false,disposition:'covered'}]),job]);
await validate();
const events=[1,2].map(id=>({accountId:'1',teamId:team,orgId:org,personId:'42',kind:'ChangeLog',upstreamId:String(id),occurredAt:`2026-01-0${id+1}T08:00:00Z`,from:'Lead',to:'Closed'}));
await db.query('select history_import_events(1,$1,$2,$3)',[team,org,JSON.stringify(events)]);
await assert.rejects(db.query('select history_project_job($1)',[job]),/Only published/);
await db.query(`insert into person_stage_log values($1,$2,42,'Closed',null,'closed','seed')`,[org,team]);
const snapshot={orgId:org,teamId:team,sourcePolicyVersion:'truehq-exact-sources-2026-v1',cohortPolicy:'created-ytd-2026-v1',through:'2026-09-12T03:00:00Z',leads:[{fub_person_id:42,team_id:team,fub_created:'2026-01-01T08:00:00Z',source_family:'Zillow'}],stageLog:[]};
const publish=(s=snapshot)=>db.query('select history_publish($1,$2,$3) result',[job,'b'.repeat(64),JSON.stringify(s)]);
await assert.rejects(publish({...snapshot,orgId:'other'}),/identity/);
await assert.rejects(publish({...snapshot,leads:[{...snapshot.leads[0],fub_created:'2025-12-31T23:59:59-08:00'}]}),/creation cohort/);
const forged={team_id:team,fub_person_id:42,event_kind:'ChangeLog',event_id:'1',changed_at:events[0].occurredAt,stage_class:'invented',basis:'closed'};
await assert.rejects(publish({...snapshot,stageLog:[forged]}),/Unevidenced/);
assert.equal((await publish()).rows[0].result.legacy_rollback_key,'pulse-history:v1:'+org);
assert.equal((await db.query('select history_project_job($1) n',[job])).rows[0].n,1);
assert.equal((await db.query('select history_project_job($1) n',[job])).rows[0].n,0);
assert.equal((await db.query('select changed_at::text d from person_stage_log')).rows[0].d,'2026-01-02 08:00:00+00');
assert.equal((await db.query('select count(*)::int n from history_stage_events')).rows[0].n,2);
assert.equal((await publish()).rows[0].result.reused,true);
await assert.rejects(publish({...snapshot,extra:'changed'}),/Immutable/);
assert.equal((await db.query('select count(*)::int n from history_publications')).rows[0].n,1);
await db.exec('reset role;set role authenticated;');await assert.rejects(publish(),/permission denied/);
await db.close();console.log('PASS: publication requires overlap, census, complete intervals, current profiles; tenant mismatch, immutable conflicts, duplicate promotion and access checks');

