import { useState } from 'react';
import { HqShell } from '../components/hqShell';
import { DeckFocusProvider } from '../components/deckFocus';
import { signOutClean } from '../lib/api';
import { parseCSV } from '../lib/csv';
import { earningsFields, reviewEarnings, earnings, csvCell, type EarningsField, type EarningsRow } from '../lib/earningsImport';
const blank=Object.fromEntries(earningsFields.map(k=>[k,k])) as Record<EarningsField,string>;
const money=(n:number)=>n.toLocaleString(undefined,{style:'currency',currency:'USD'});
function download(name:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export default function Earnings({org}:{org:{id:string;name:string}}){
  const [text,setText]=useState(''),[file,setFile]=useState(''),[mapping,setMapping]=useState(blank),[share,setShare]=useState(''),[rows,setRows]=useState<EarningsRow[]>([]),[errors,setErrors]=useState<string[]>([]),[accepted,setAccepted]=useState(false),[filter,setFilter]=useState('');
  const headers=parseCSV(text)?.headers??[];
  const visible=rows.filter(r=>!filter||r.agent===filter);
  const retained=visible.reduce((s,r)=>s+earnings(r).retained,0),complete=visible.filter(r=>r.expenses!==null);
  const go=(r:string)=>{window.location.hash=r;};
  return <DeckFocusProvider><div className="tru-dark pulse-refined"><HqShell orgName={org.name} hideTopbar onSignOut={signOutClean} nav={{onOpenPulse:()=>go('/pulse'),onOpenCoach:()=>go('/coach'),onOpenRep:()=>go('/rep'),onOpenTeam:()=>go('/team')}}><main className="dk-main earnings-page">
    <header className="pulse-heading"><div><span className="pulse-kicker">Earnings</span><h1>Know what the business kept.</h1><p>Reviewable estimates from your closing statement. USD.</p></div><button className="brief-open" onClick={()=>go('/pulse')}>Back to Pulse</button></header>
    <p>This preview processes files in this page only. Nothing is uploaded or saved; export your statement before leaving. Imported values are not independently verified.</p>
    <details open={!accepted} className="earnings-import"><summary>Import a closing statement</summary><p>One row per deal side. Use a unique deal-side ID and YYYY-MM-DD closing dates. Referral fees come off gross commission before the brokerage share is applied. Enter 0 explicitly for no referral fee. Missing expenses stay unknown.</p>
      <button className="brief-open" onClick={()=>download('tru-earnings-template.csv',earningsFields.join(',')+'\n')}>Download blank CSV template</button>
      <label>Choose CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5000000){setErrors(['File exceeds 5 MB.']);return;}try{setText(await f.text());setFile(f.name);setRows([]);setAccepted(false);setErrors([]);}catch{setErrors(['File could not be read.']);}}}/></label>
      {text&&<><p>{file}</p><div className="earnings-mapping">{earningsFields.map(k=><label key={k}>{k.replace(/_/g,' ')}<select value={headers.includes(mapping[k])?mapping[k]:''} onChange={e=>{setMapping({...mapping,[k]:e.target.value});setAccepted(false);setRows([]);}}><option value="">Not mapped</option>{headers.map((h,i)=><option key={i} value={h}>{h}</option>)}</select></label>)}</div>
      <label>Default brokerage share % (only when a row has no share)<input type="number" min="0" max="100" step="0.01" value={share} onChange={e=>{setShare(e.target.value);setAccepted(false);setRows([]);}}/></label>
      <button className="brief-open" onClick={()=>{const result=reviewEarnings(text,mapping,share);setRows(result.rows);setErrors(result.errors);setAccepted(false);}}>Review calculations</button></>}
    </details>
    {!!errors.length&&<div role="alert"><p>Correct these rows before accepting the statement. No partial import is accepted.</p>{errors.slice(0,20).map((e,i)=><p key={i}>{e}</p>)}{errors.length>20&&<p>{errors.length-20} more errors.</p>}</div>}
    {!!rows.length&&<><div className="earnings-actions"><label>Agent<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All agents</option>{[...new Set(rows.map(r=>r.agent))].sort().map(a=><option key={a}>{a}</option>)}</select></label><span>{rows.length} rows · {accepted?'Accepted for this preview':'Awaiting your review'}</span>{!accepted&&<button disabled={!!errors.length} onClick={()=>setAccepted(true)}>Accept reviewed statement</button>}{accepted&&<button onClick={()=>download('tru-earnings-statement.csv',[['deal_id','agent','closed_date','source','gross_commission','referral_fee','broker_share_pct','brokerage_share','entered_expenses','contribution_after_entered_expenses','input_status','source_file','source_row'],...visible.map(r=>[r.id,r.agent,r.date,r.source,r.gross,r.referral,r.share,earnings(r).retained,r.expenses,earnings(r).contribution,'User-reviewed import',file,r.line])].map(r=>r.map(csvCell).join(',')).join('\r\n'))}>Export statement</button>}</div>
      <section className="pulse-summary"><div><span>Imported gross commission</span><strong>{money(visible.reduce((s,r)=>s+r.gross,0))}</strong></div><div><span>Estimated brokerage share</span><strong>{money(retained)}</strong></div><div><span>Known contribution subtotal</span><strong>{complete.length?money(complete.reduce((s,r)=>s+earnings(r).contribution!,0)):'—'}</strong><small>{complete.length} of {visible.length} rows include expenses. Not net profit.</small></div></section>
      <div className="operations-table"><table><thead><tr><th>Deal / source</th><th>Agent</th><th>Closed</th><th>Gross</th><th>Referral fee</th><th>Brokerage %</th><th>Expenses</th><th>Brokerage share</th><th>Contribution</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.id}<small>{r.source} · CSV row {r.line}</small></td><td>{r.agent}</td><td>{r.date}</td><td>{money(r.gross)}</td><td>{money(r.referral)}</td><td><input aria-label={'Brokerage share for '+r.id} type="number" min="0" max="100" step="0.01" value={r.share} onChange={e=>{const n=e.target.valueAsNumber;if(!Number.isFinite(n)||n<0||n>100)return;setRows(rows.map(v=>v.id===r.id?{...v,share:n}:v));setAccepted(false);}}/></td><td>{r.expenses===null?'Not supplied':money(r.expenses)}</td><td>{money(earnings(r).retained)}</td><td>{earnings(r).contribution===null?'Unknown':money(earnings(r).contribution!)}</td></tr>)}</tbody></table></div>
      <p>Calculation for each row: (gross commission − referral fee) × brokerage share percentage − entered expenses. Organization overhead, taxes and unentered costs are excluded.</p>
    </>}
  </main></HqShell></div></DeckFocusProvider>;
}
