// @vitest-environment jsdom
import {act} from 'react';
import {createRoot, type Root} from 'react-dom/client';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {Activity,PracticeGroups,ResponseWorkspace,SimpleLiveStage,PresenterSpeakingNotes} from './LiveSessions';
import {getWorkshopDefinition} from '../../../shared/workshopCatalog';
import {liveDraftKey, type LiveSessionState} from '../../../shared/liveWorkshops';
const mocks=vi.hoisted(()=>({request:vi.fn(async(..._args:unknown[])=>({})),submit:vi.fn(async()=>({id:'saved',grade:null}))}));
vi.mock('../lib/liveSessions',async(original)=>({...await original<any>(),liveRequest:mocks.request,sessionCommand:(id:string,command:unknown)=>mocks.request(`/${id}/commands`,command),submitAttempt:mocks.submit}));
describe('live short-answer continuation',()=>{
 let root:Root,container:HTMLDivElement;
 const slide=getWorkshopDefinition(1)!.slides.find(s=>s.activity?.fields?.some(f=>f.id==='readiness'))!;
 const state={viewerId:'user',myAgentId:'learner',session:{id:'session',version:'test'},attempts:[],observations:[],revealedActivityIds:[]} as unknown as LiveSessionState;
 const key=liveDraftKey('user','session','test',slide.activity!.id);
 beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);localStorage.clear();mocks.submit.mockClear();container=document.createElement('div');document.body.append(container);root=createRoot(container);});
 afterEach(async()=>{await act(async()=>root.unmount());document.body.replaceChildren();vi.unstubAllGlobals();});
 it.each(['','I do not know.','I would ignore the source.'])('can continue with any draft without submitting or losing it: %s',async answer=>{
  const draft={'readiness':answer};localStorage.setItem(key,JSON.stringify(draft));const onContinue=vi.fn();
  await act(async()=>root.render(<Activity state={state} slide={slide} activity={slide.activity!} refresh={()=>{}} onContinue={onContinue}/>));
  const button=[...container.querySelectorAll('button')].find(b=>b.textContent==='Continue with presenter')!;
  expect(button.disabled).toBe(false);
  await act(async()=>button.click());
  expect(onContinue).toHaveBeenCalledOnce();expect(mocks.submit).not.toHaveBeenCalled();
  expect(JSON.parse(localStorage.getItem(key)!)).toEqual(draft);
 });
 it('submits an opinion unchanged without requiring a correct answer',async()=>{
  const draft={'readiness':'I would ignore the source.'};localStorage.setItem(key,JSON.stringify(draft));
  await act(async()=>root.render(<Activity state={state} slide={slide} activity={slide.activity!} refresh={()=>{}} onContinue={()=>{}}/>));
  const button=[...container.querySelectorAll('button')].find(b=>b.textContent==='Submit response')!;
  expect(button.disabled).toBe(false);await act(async()=>button.click());
  expect(mocks.submit).toHaveBeenCalledWith('session',key,slide.activity!.id,draft);
  expect(container.textContent).toContain('Submitted');
 });
 it('shows presenter feedback only for this learner and activity',async()=>{
  const observation={id:'feedback',agentId:'learner',activityId:slide.activity!.id,coachReviewed:true,round:1,correction:'Ask what more space would change.',retry:'Asked about garden plans.',retryObserved:true};
  const value={...state,observations:[observation,{...observation,id:'private',agentId:'someone-else',correction:'Private feedback'},{...observation,id:'other',activityId:'other-activity',correction:'Other activity feedback'}]} as LiveSessionState;
  await act(async()=>root.render(<Activity state={value} slide={slide} activity={slide.activity!} refresh={()=>{}} onContinue={()=>{}}/>));
  expect(container.textContent).toContain('Presenter feedback');
  expect(container.textContent).toContain('Ask what more space would change.');
  expect(container.textContent).toContain('Asked about garden plans.');
  expect(container.textContent).not.toContain('Private feedback');
  expect(container.textContent).not.toContain('Other activity feedback');
 });
 it.each(['learner','buyer'])('shows the full-call case and reserves buyer instructions for the buyer: %s',async viewer=>{
  const definition=getWorkshopDefinition(2)!;const activityId='day2-full-call-practice';
  const value={...state,myAgentId:viewer,definition,participants:[],groups:[{id:'group',activityId,round:1,agentId:'learner',buyerId:'buyer',observerId:null}]} as LiveSessionState;
  await act(async()=>root.render(<PracticeGroups state={value} activityId={activityId}/>));
  expect(container.textContent).toContain(definition.cases![0].quote);
  expect(container.textContent?.includes(definition.cases![0].goal)).toBe(viewer==='buyer');
 });
 it.each(['day2-objection-practice','day2-channel-check'])('submits from the presentation response panel: %s',async slideId=>{
  const definition=getWorkshopDefinition(2)!;
  const current=definition.slides.find(s=>s.id===slideId)!;
  const activity=current.activity!;
  const value={...state,definition,session:{...state.session,currentSlideId:slideId},openedActivityIds:[activity.id],groups:[],participants:[]} as LiveSessionState;
  const response=Object.fromEntries((activity.fields||[]).map(f=>[f.id,'Please call after 5. I will confirm that time.']));
  if(activity.choices?.length)response.choiceId=activity.choices[0].id;
  const draftKey=liveDraftKey('user','session','test',activity.id);
  localStorage.setItem(draftKey,JSON.stringify(response));
  await act(async()=>root.render(<ResponseWorkspace state={value} refresh={()=>{}}/>));
  expect(container.querySelector('[data-slide]')).toBeNull();
  if(activity.choices?.length)expect(container.querySelectorAll('input[type=radio]').length).toBe(activity.choices.length);
  if(activity.fields?.length)expect(container.querySelectorAll('textarea').length).toBe(activity.fields.length);
  const submit=[...container.querySelectorAll('button')].find(b=>b.textContent==='Submit response')!;
  expect(submit.disabled).toBe(false);
  await act(async()=>submit.click());
  expect(mocks.submit).toHaveBeenCalledWith('session',draftKey,activity.id,response);
  expect(container.textContent).toContain('Submitted');
 });
 it('follows the current slide without requiring a learner selection',async()=>{
  const definition=getWorkshopDefinition(2)!;
  const value={...state,definition,session:{...state.session,currentSlideId:'day2-objection-practice'},openedActivityIds:['day2-objection-practice','day2-channel-check'],groups:[]} as LiveSessionState;
  await act(async()=>root.render(<ResponseWorkspace state={value} refresh={()=>{}}/>));
  expect(container.querySelectorAll('input[type=radio]')).toHaveLength(3);
  expect([...container.querySelectorAll('.live-choice-list label')].map(e=>e.textContent)).toEqual(definition.slides.find(s=>s.id==='day2-objection-practice')!.activity!.choices!.map(c=>c.text));
  expect(container.textContent).not.toContain('Continue with presenter');
  await act(async()=>root.render(<ResponseWorkspace state={{...value,session:{...value.session,currentSlideId:'day2-channel-check'}}} refresh={()=>{}}/>));
  expect(container.querySelectorAll('input[type=radio]')).toHaveLength(3);
  expect(container.querySelectorAll('textarea')).toHaveLength(1);
  expect(container.querySelector('select')).toBeNull();
 });
 it('shows arriving answers for the current slide without exposing them on the shared screen',async()=>{
  vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){}});
  const definition=getWorkshopDefinition(2)!;
  const value={...state,definition,canPresent:true,session:{...state.session,currentSlideId:'day2-objection-practice',status:'active'},openedActivityIds:['day2-objection-practice'],groups:[],participants:[{agentId:'learner',name:'Test learner'}],choiceTotals:{}} as unknown as LiveSessionState;
  await act(async()=>root.render(<SimpleLiveStage state={value} view="presenter" refresh={()=>{}}/>));
  expect(container.textContent).toContain('Answers · 0 / 1');
  const withAnswer={...value,attempts:[{id:'submitted',agentId:'learner',activityId:'day2-objection-practice',attempt:1,response:{choiceId:'understand'},grade:null,assisted:false,submittedAt:new Date().toISOString()}]};
  await act(async()=>root.render(<SimpleLiveStage state={withAnswer} view="presenter" refresh={()=>{}}/>));
  expect(container.textContent).toContain('Answers · 1 / 1');
  expect(container.querySelector('select')).toBeNull();
  expect(container.querySelector('[aria-label="Current question responses"]')?.textContent).toContain('After that experience');
  await act(async()=>root.render(<SimpleLiveStage state={withAnswer} view="shared" refresh={()=>{}}/>));
  expect(container.querySelector('[aria-label="Current question responses"]')).toBeNull();
  expect(container.textContent).not.toContain('Test learner');
 });
 it('selects discussion choices without submitting learner evidence and syncs the share window',async()=>{
  vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){}});
  const definition=getWorkshopDefinition(2)!;
  const value={...state,definition,canPresent:true,session:{...state.session,currentSlideId:'day2-lead-discussion',status:'active'},openedActivityIds:['day2-lead-discussion'],groups:[],participants:[],choiceTotals:{}} as unknown as LiveSessionState;
  await act(async()=>root.render(<SimpleLiveStage state={value} view="presenter" refresh={()=>{}}/>));
  const options=container.querySelectorAll<HTMLButtonElement>('.live-discussion-choice');
  expect(options).toHaveLength(4);
  await act(async()=>options[1].click());
  expect(options[1].getAttribute('aria-pressed')).toBe('true');
  expect(mocks.submit).not.toHaveBeenCalled();
  await act(async()=>root.render(<SimpleLiveStage state={value} view="shared" refresh={()=>{}}/>));
  expect(container.querySelector('.discussion-selected')?.textContent).toContain('Within 10 minutes');
  await act(async()=>window.dispatchEvent(new StorageEvent('storage',{key:'tru-discussion-choice:session:day2-lead-discussion',newValue:'five'})));
  expect(container.querySelector('.discussion-selected')?.textContent).toContain('Within 5 minutes');
  await act(async()=>root.render(<SimpleLiveStage state={{...value,session:{...value.session,currentSlideId:'day2-channel-check'}}} view="presenter" refresh={()=>{}}/>));
  expect(container.querySelector('.discussion-selected')).toBeNull();
 });
 it('submits a presenter group answer only after selection and supports retry after failure',async()=>{
  vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){}});
  mocks.request.mockClear();
  const refresh=vi.fn();
  const definition=getWorkshopDefinition(2)!;
  const value={...state,definition,canPresent:true,session:{...state.session,currentSlideId:'day2-lead-discussion',status:'active'},openedActivityIds:['day2-lead-discussion'],groups:[],participants:[],choiceTotals:{}} as unknown as LiveSessionState;
  await act(async()=>root.render(<SimpleLiveStage state={value} view="presenter" refresh={refresh}/>));
  const submit=()=>[...container.querySelectorAll('button')].find(b=>b.textContent==='Submit answer')!;
  expect(submit().disabled).toBe(true);
  await act(async()=>container.querySelectorAll<HTMLButtonElement>('.live-discussion-choice')[1].click());
  expect(submit().disabled).toBe(false);
  mocks.request.mockRejectedValueOnce(new Error('Connection lost'));
  await act(async()=>submit().click());
  expect(container.querySelector('[role="alert"]')?.textContent).toContain('Connection lost');
  expect(submit().disabled).toBe(false);
  expect(refresh).not.toHaveBeenCalled();
  await act(async()=>submit().click());
  expect(mocks.request).toHaveBeenLastCalledWith('/session/commands',{action:'reveal',activityId:'day2-lead-discussion'});
  expect(refresh).toHaveBeenCalledTimes(1);
  expect(container.textContent).toContain('Answer submitted');
  expect(mocks.submit).not.toHaveBeenCalled();
  expect(container.querySelector('a[href*="notes=1"]')?.getAttribute('target')).toBe('_blank');
  await act(async()=>root.render(<SimpleLiveStage state={value} view="shared" refresh={refresh}/>));
  expect(container.querySelector('a[href*="notes=1"]')).toBeNull();
 });
 it('follows slides with plain-language private notes and rejects non-presenters',async()=>{
  const definition=getWorkshopDefinition(2)!;
  const value={...state,definition,canPresent:true,session:{...state.session,currentSlideId:'day2-alms'}} as LiveSessionState;
  await act(async()=>root.render(<PresenterSpeakingNotes state={value}/>));
  expect(container.textContent).toContain('LEAD gives us a simple order.');
  expect(container.textContent).toContain('What to say');
  expect(container.textContent).not.toContain('INT-016');
  await act(async()=>root.render(<PresenterSpeakingNotes state={{...value,session:{...value.session,currentSlideId:'day2-reference'}}}/>));
  expect(container.textContent).toContain('Slide 25 of 25');
  expect(container.textContent).toContain('Which part would you like to practice again');
  expect(container.textContent).toContain('Close the session');
  await act(async()=>root.render(<PresenterSpeakingNotes state={{...value,canPresent:false}}/>));
  expect(container.querySelector('[role="alert"]')?.textContent).toContain('Only the presenter');
  expect(container.textContent).not.toContain('LEAD gives us');
 });
 it('does not expose a response form before the activity opens',async()=>{
  const definition=getWorkshopDefinition(2)!;
  const value={...state,definition,session:{...state.session,currentSlideId:'day2-objection-practice'},openedActivityIds:[],groups:[]} as LiveSessionState;
  await act(async()=>root.render(<ResponseWorkspace state={value} refresh={()=>{}}/>));
  expect(container.textContent).toContain('Waiting for the presenter');
  expect(container.querySelector('input')).toBeNull();
 });

});
