import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { DEFAULT_PROFILE, PROFILE_THEMES, type PersonalProfile as Profile, type ProfileSection } from '../../../shared/agentProfile';
import { isDemo } from '../lib/api';
import { deletePersonalProfile, prepareProfilePhoto, readPersonalProfile, savePersonalProfile, type ProfileRecord } from '../lib/personalProfile';
import './personalProfile.css';
import AchievementEmblem from '../components/AchievementEmblem';

const LABELS: Record<ProfileSection, string> = { about: 'About', interests: 'Interests', gallery: 'Photos', achievements: 'Accomplishments', goals: 'Goals' };
const INTERESTS = ['Hiking', 'Coffee', 'Cooking', 'Travel', 'Dogs', 'Gardening', 'Live music', 'Architecture', 'Fitness', 'Photography', 'Reading', 'Family', 'Volunteering', 'Sports', 'Art', 'The outdoors'];

export default function PersonalProfile({ name, onDirtyChange }: { name: string; onDirtyChange: (dirty: boolean) => void }) {
  const [record, setRecord] = useState<ProfileRecord | null>(null);
  const [draft, setDraft] = useState<Profile | null>(null);
  const [editing, setEditing] = useState(false);
  const [panel, setPanel] = useState('About');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [interest, setInterest] = useState('');
  const [savedMessage, setSavedMessage] = useState('');
  const [deleteText, setDeleteText] = useState('');
  const [deleting, setDeleting] = useState(false);
  const [openPhoto, setOpenPhoto] = useState<{image:string;caption:string}|null>(null);
  const photoDialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(openPhoto)photoDialog.current?.showModal();else photoDialog.current?.close();},[openPhoto]);
  const [discarding, setDiscarding] = useState(false);
  const saving = useRef(false);
  const alive = useRef(true);
  const editorRef = useRef<HTMLElement>(null);
  const dirty = !!record && !!draft && JSON.stringify(record.profile) !== JSON.stringify(draft);
  useEffect(() => { alive.current = true; void readPersonalProfile().then(r => { if (alive.current) { setRecord(r); setDraft(r.profile); } }).catch(e => { if (alive.current) setError(e.message); }); return () => { alive.current = false; }; }, []);
  useEffect(() => { onDirtyChange(dirty || busy || uploading); return () => onDirtyChange(false); }, [dirty, busy, uploading, onDirtyChange]);
  useEffect(() => { if (!dirty) return; const guard = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [dirty]);
  const update = <K extends keyof Profile>(key: K, value: Profile[K]) => { setDraft(p => p ? { ...p, [key]: value } : p); setSavedMessage(''); };
  const finishEditing = () => { if (record) setDraft(record.profile); setEditing(false); setDiscarding(false); setError(''); };
  const removeProfile = async () => {
    if(deleteText!=='DELETE'||saving.current)return;
    saving.current=true;setBusy(true);setError('');
    try{await deletePersonalProfile();const empty={profile:structuredClone(DEFAULT_PROFILE),updatedAt:null,badges:[]};setRecord(empty);setDraft(empty.profile);setEditing(false);setDeleting(false);setDeleteText('');setOpenPhoto(null);setSavedMessage('Your profile has been deleted. Your login and original training records are unchanged.');}
    catch(e){setError(e instanceof Error?e.message:'Your profile could not be deleted.');}
    finally{saving.current=false;setBusy(false);}
  };
  const save = async () => {
    if (!draft || saving.current || uploading) return;
    if(draft.termsVersion!=='2026-09-06'){setError('Please agree to the profile content terms before saving.');return;}
    saving.current = true; setBusy(true); setError('');
    try { const saved = await savePersonalProfile(draft); if (alive.current) { setRecord(r => r ? { ...r, ...saved } : r); setDraft(saved.profile); setEditing(false); setSavedMessage(isDemo ? 'Demo changes saved in this browser.' : 'Your profile is saved.'); } }
    catch (e) { if (alive.current) setError(e instanceof Error ? e.message : 'Your changes could not be saved.'); }
    finally { saving.current = false; if (alive.current) setBusy(false); }
  };
  const photo = async (file: File | undefined, field: 'portrait' | 'cover' | 'gallery', index?: number) => {
    if (!file || uploading || !draft) return;
    setUploading(true); setError('');
    try { const image = await prepareProfilePhoto(file, field === 'portrait' ? 480 : field === 'cover' ? 1280 : 900); if (alive.current) { if (field === 'gallery') setDraft(p => p ? { ...p, gallery: index === undefined ? [...p.gallery, { image, caption: '' }].slice(0, 3) : p.gallery.map((g, i) => i === index ? { ...g, image } : g) } : p); else update(field, image); } }
    catch (e) { setError(e instanceof Error ? e.message : 'That photo could not be opened.'); }
    finally { if (alive.current) setUploading(false); }
  };
  if (!record || !draft) return <div className="pp-loading" role="status">{error ? <><p role="alert">{error}</p><button onClick={() => { setError(''); void readPersonalProfile().then(r => { setRecord(r); setDraft(r.profile); }).catch(e => setError(e.message)); }}>Try again</button></> : 'Opening your profile…'}</div>;
  const p = editing ? draft : record.profile;
  const titleFor=(section:ProfileSection)=>p.sectionTitles[section]||LABELS[section];
  const hasContent=(section:ProfileSection)=>section==='about'?!!(p.bio||p.markets||p.favorite):section==='interests'?!!p.interests.length:section==='gallery'?!!p.gallery.length:section==='achievements'?!!record.badges.length:!!p.goal;
  const start=(nextPanel:string)=>{setEditing(true);setPanel(nextPanel);setError('');};
  const initials = name.split(/\s+/).map(n => n[0]).slice(0, 2).join('');
  const move = (section: ProfileSection, direction: number) => { const next = [...draft.sections]; const from = next.indexOf(section), to = from + direction; if (to < 0 || to >= next.length) return; [next[from], next[to]] = [next[to], next[from]]; update('sections', next); };
  const addInterest = (value: string) => { const text = value.trim(); if (text && draft.interests.length < 8 && !draft.interests.some(i => i.toLowerCase() === text.toLowerCase())) update('interests', [...draft.interests, text]); setInterest(''); };
  const field = (key: 'headline' | 'bio' | 'location' | 'markets' | 'careerStart' | 'goal' | 'favorite', label: string, limit: number, multiline = false) => <label className="pp-field">{label}{multiline ? <textarea value={draft[key]} maxLength={limit} rows={key === 'bio' ? 6 : 3} onChange={e => update(key, e.target.value)} /> : <input value={draft[key]} maxLength={limit} inputMode={key === 'careerStart' ? 'numeric' : 'text'} onChange={e => update(key, e.target.value)} />}<span>{draft[key].length}/{limit}</span></label>;
  const upload = (label: string, target: 'portrait' | 'cover' | 'gallery', index?: number) => <label className="pp-upload">{label}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading || busy} onChange={e => { void photo(e.target.files?.[0], target, index); e.target.value = ''; }} /></label>;
  return <div className={`personal-profile ${editing ? 'pp-editing' : ''}`}>
    <div className="pp-toolbar"><div><span className="pp-private">{isDemo ? 'Demo profile' : 'Private profile'}</span><p>{isDemo ? 'Fictional sample agent. Demo photos are generated. Changes stay in this browser.' : 'Other agents cannot browse your profile.'}</p></div><button className="pp-primary" onClick={() => { if (editing) editorRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); else { setEditing(true); setError(''); setSavedMessage(''); } }}>{editing ? 'Back to editor' : record.updatedAt ? 'Edit profile' : 'Edit profile'} <span aria-hidden>↗</span></button></div>
    {!record.updatedAt&&!editing&&<section className="pp-start"><h2>Add your details</h2><p>Add a photo, write a little about yourself, and choose a few interests. Everything else is optional.</p><div><button onClick={()=>start('Photos')}>{p.portrait?'✓ Photo added':'1. Add a photo'}</button><button onClick={()=>start('About')}>{p.bio?'✓ About you added':'2. Introduce yourself'}</button><button onClick={()=>start('Interests')}>{p.interests.length?'✓ Interests added':'3. Pick your interests'}</button></div></section>}
    {savedMessage && <p className="pp-feedback" role="status">✓ {savedMessage}</p>}
    {error && <p className="pp-error" role="alert">{error}</p>}
    <div className="pp-workspace">
      <article className={`pp-page pp-theme-${p.theme} pp-font-${p.font} pp-layout-${p.layout}`} style={{ '--pp-accent': p.accent } as CSSProperties} aria-label={`${name}’s profile`}>
        <div className={`pp-cover pp-cover-${p.coverStyle} ${p.cover ? 'pp-cover-photo' : 'pp-cover-minimal'}`}>
          {p.cover ? <img src={p.cover} alt="Profile cover" style={{objectPosition:`50% ${p.coverPosition}%`}} /> : <div className="pp-cover-art" aria-hidden><i /><i /><i /></div>}
        </div>
        <header className="pp-identity">
          <div className="pp-name"><h2>{name}</h2>{p.headline&&<p className="pp-headline">{p.headline}</p>}<div className="pp-meta">{p.location && <span>{p.location}</span>}{p.careerStart && <span>In real estate since {p.careerStart} <small>· added by you</small></span>}</div></div>
          <div className={`pp-portrait ${p.portrait?'':'pp-portrait-initials'}`}>{p.portrait ? <img src={p.portrait} alt={name} style={{objectPosition:`50% ${p.portraitPosition}%`}} /> : <span>{initials}</span>}</div>
        </header>
        <div className="pp-sections">{(['achievements', ...p.sections.filter(s => s !== 'achievements')] as ProfileSection[]).filter(s => !p.hidden.includes(s) && (editing || hasContent(s))).map(section => <section key={section} className={`pp-section pp-section-${section}`}><div className="pp-section-heading"><h3>{titleFor(section)}</h3></div><div className="pp-section-content">
          {section === 'about' && <><p className="pp-bio">{p.bio || 'Add a short introduction in the About settings.'}</p>{p.markets && <div className="pp-markets"><span>WHERE I WORK</span><p>{p.markets}</p></div>}{p.favorite && <blockquote><span>A small thing I love</span>{p.favorite}</blockquote>}</>}
          {section === 'interests' && (p.interests.length ? <ul className="pp-interests">{p.interests.map(item => <li key={item}>{item}</li>)}</ul> : <p className="pp-empty">Choose your interests in the editor.</p>)}
          {section === 'gallery' && (p.gallery.length ? <div className="pp-gallery">{p.gallery.map((g, i) => <figure key={i}><button className="pp-photo-open" onClick={()=>setOpenPhoto(g)} aria-label={`Open ${g.caption || `photo ${i+1}`} full size`}><img src={g.image} alt={g.caption || `Personal photo ${i + 1}`} loading="lazy" /><span aria-hidden>↗</span></button><figcaption>{g.caption}</figcaption></figure>)}</div> : <div className="pp-camera-empty"><span aria-hidden>▧</span><p>Add up to three photos with captions.</p></div>)}
          {section === 'achievements' && <>{record.badges.length ? <div className="pp-badges">{record.badges.map(b => <div className={`pp-badge pp-badge-${b.kind}`} key={b.id}><AchievementEmblem badge={b} /><div><span className="pp-overline">{isDemo ? 'Sample award' : b.kind === 'training' ? 'Training completed' : 'Contract milestone'}</span><h4>{b.title}</h4><p>{b.detail}</p>{b.verifiedAt&&Number.isFinite(Date.parse(b.verifiedAt))&&<time dateTime={b.verifiedAt}>Recorded {new Date(b.verifiedAt).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}</time>}</div></div>)}</div> : <p className="pp-empty">Your first accomplishment belongs here. Badges appear when TRU verifies a completed training assessment or a contract milestone.</p>}{record.badgeNotice && <p className="pp-empty">{record.badgeNotice}</p>}<p className="pp-badge-note">{isDemo ? 'Sample accomplishments for this preview.' : 'Earned badges stay with your profile. Contract milestones reflect the leads assigned to you in TRU’s imported history.'}</p></>}
          {section === 'goals' && <div className="pp-goal"><p>{p.goal || 'What would you like to make happen next?'}</p></div>}
        </div></section>)}</div><footer className="pp-page-footer"><span>{name}</span><strong>TRU</strong></footer>
      </article>
      {editing && <aside className="pp-editor" ref={editorRef} aria-label="Edit your profile"><header><h2>Edit your profile</h2><p>Changes appear in the preview as you go.</p><button className="pp-secondary pp-preview-jump" onClick={() => document.querySelector('.pp-page')?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>View preview ↓</button></header><div className="pp-editor-tabs" aria-label="Profile settings">{['About', 'Look', 'Interests', 'Photos', 'Layout', 'Privacy'].map(t => <button key={t} aria-pressed={panel === t} onClick={() => setPanel(t)}>{t}</button>)}</div>
        <fieldset disabled={busy || uploading} className="pp-fields"><legend className="pp-sr-only">{panel} settings</legend>
        {panel === 'About' && <>{field('headline', 'Introduction', 100)}{field('bio', 'Your story', 1200, true)}{field('location', 'Home base', 80)}{field('markets', 'Where you work', 160)}{field('careerStart', 'Year you started in real estate', 4)}<p className="pp-help">This year is shown as information you provided.</p>{field('favorite', 'A small thing you love', 160)}{field('goal', 'What you’re working toward', 280, true)}</>}
        {panel === 'Look' && <><h3>Colors</h3><div className="pp-theme-options">{PROFILE_THEMES.map(t => <button key={t} className={`pp-swatch pp-swatch-${t}`} aria-pressed={draft.theme === t} onClick={() => update('theme', t)}><i /><span>{t}</span>{draft.theme === t && <b aria-hidden>✓</b>}</button>)}</div><label className="pp-field">Type style<select value={draft.font} onChange={e => update('font', e.target.value as Profile['font'])}><option value="classic">Classic · friendly & familiar</option><option value="modern">Modern · clean & simple</option><option value="editorial">Editorial · a little character</option></select></label><label className="pp-field">Cover pattern<select value={draft.coverStyle} onChange={e => update('coverStyle', e.target.value as Profile['coverStyle'])}><option value="orbit">Orbit</option><option value="waves">Waves</option><option value="grid">Grid</option></select></label><label className="pp-field pp-color">Personal accent<input type="color" value={draft.accent} onChange={e => update('accent', e.target.value)} /></label><p className="pp-help">Your accent colors the cover artwork. Each theme keeps text easy to read.</p></>}
        {panel === 'Interests' && <><h3>Interests</h3><p className="pp-help">Choose up to eight. Make room by removing one.</p><div className="pp-interest-choices">{INTERESTS.map(item => <button key={item} aria-pressed={draft.interests.includes(item)} disabled={!draft.interests.includes(item) && draft.interests.length >= 8} onClick={() => draft.interests.includes(item) ? update('interests', draft.interests.filter(i => i !== item)) : addInterest(item)}>{item}</button>)}</div><label className="pp-field">Add your own<input value={interest} maxLength={32} onChange={e => setInterest(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addInterest(interest); } }} /></label><button className="pp-secondary" disabled={!interest.trim() || draft.interests.length >= 8} onClick={() => addInterest(interest)}>Add interest</button><div className="pp-selected">{draft.interests.map(i => <button key={i} onClick={() => update('interests', draft.interests.filter(item => item !== i))} aria-label={`Remove ${i}`}>{i} ×</button>)}</div><p className="pp-help">{draft.interests.length} of 8 selected</p></>}
        {panel === 'Photos' && <><p className="pp-upload-notice">Your photos personalize your profile. Other agents cannot view them here. Upload photos you have permission to use, and keep client documents out. Remove a photo and save to delete it from your profile. <a href="/privacy#profiles" target="_blank" rel="noreferrer">Privacy details</a></p><p className="pp-help">JPG, PNG, or WebP. Up to 12 MB each; we resize them for your page.</p><h3>Your portrait</h3>{draft.portrait && <img className="pp-photo-thumb" src={draft.portrait} alt="Portrait preview" />}{upload(draft.portrait ? 'Change portrait' : 'Choose portrait', 'portrait')}{draft.portrait&&<label className="pp-field">Portrait framing<input type="range" min="0" max="100" value={draft.portraitPosition} onChange={e=>update('portraitPosition',Number(e.target.value))}/><span>Move the visible area up or down</span></label>}{draft.portrait && <button className="pp-remove" onClick={() => update('portrait', '')}>Remove portrait</button>}<h3>Cover photo</h3>{draft.cover && <img className="pp-photo-thumb pp-thumb-wide" src={draft.cover} alt="Cover preview" />}{upload(draft.cover ? 'Change cover' : 'Choose cover photo', 'cover')}{draft.cover&&<label className="pp-field">Cover framing<input type="range" min="0" max="100" value={draft.coverPosition} onChange={e=>update('coverPosition',Number(e.target.value))}/><span>Move the visible area up or down</span></label>}{draft.cover && <button className="pp-remove" onClick={() => update('cover', '')}>Use pattern instead</button>}<h3>Camera roll</h3>{draft.gallery.map((g, i) => <div className="pp-photo-edit" key={i}><img className="pp-photo-thumb" src={g.image} alt={`Photo ${i + 1}`} /><label className="pp-field">Caption for photo {i + 1}<input maxLength={60} value={g.caption} onChange={e => update('gallery', draft.gallery.map((item, n) => n === i ? { ...item, caption: e.target.value } : item))} /></label><button className="pp-remove" onClick={() => update('gallery', draft.gallery.filter((_, n) => n !== i))}>Remove photo {i + 1}</button></div>)}{draft.gallery.length < 3 && upload('Add personal photo', 'gallery')}</>}
        {panel === 'Layout' && <><label className="pp-field">Page layout<select value={draft.layout} onChange={e=>{const layout=e.target.value as Profile['layout'];setDraft(d=>d?{...d,layout,sections:layout==='photos'?['gallery',...d.sections.filter(s=>s!=='gallery')]:d.sections}:d);}}><option value="story">Story — room for your words</option><option value="photos">Photos — larger images first</option><option value="compact">Compact — a shorter professional page</option></select></label><h3>Section order</h3><p className="pp-help">Accomplishments stay at the top. Move the other sections or hide any section; its content is kept.</p><div className="pp-layout">{draft.sections.map((s, i) => <div key={s}><label><input type="checkbox" checked={!draft.hidden.includes(s)} onChange={e => update('hidden', e.target.checked ? draft.hidden.filter(h => h !== s) : [...draft.hidden, s])} />{LABELS[s]}</label><label className="pp-title-field"><span>Section title: {LABELS[s]}</span><input maxLength={48} placeholder={LABELS[s]} value={draft.sectionTitles[s]||''} onChange={e=>update('sectionTitles',{...draft.sectionTitles,[s]:e.target.value})}/></label><div><button disabled={i === 0 || s === 'achievements'} onClick={() => move(s, -1)} aria-label={`Move ${LABELS[s]} up`}>↑</button><button disabled={i === 4 || s === 'achievements'} onClick={() => move(s, 1)} aria-label={`Move ${LABELS[s]} down`}>↓</button></div></div>)}</div></>}
        {panel==='Privacy'&&<div className="pp-privacy-settings"><h3>Your profile information</h3><p>Other agents and team leaders cannot browse this profile. Authorized TRU staff and hosting providers may access information to operate, support, or secure the service.</p><p>Profile content has no automatic expiry. You can remove photos and details and save, or delete the whole profile below.</p><a href="/privacy#profiles" target="_blank" rel="noreferrer">Read the profile privacy notice ↗</a><h3>Delete profile</h3><p>Deletes photos, text, preferences, and saved badge copies. Your login, training results, coaching records, and original transaction records remain. If you create a profile again, badges can be calculated again from those records.</p>{!deleting?<button className="pp-secondary" onClick={()=>setDeleting(true)}>Delete profile…</button>:<div className="pp-delete-confirm"><label className="pp-field">Type DELETE to confirm<input value={deleteText} onChange={e=>setDeleteText(e.target.value)} autoComplete="off"/></label><button className="pp-danger" disabled={deleteText!=='DELETE'||busy} onClick={()=>void removeProfile()}>{busy?'Deleting…':'Permanently delete profile'}</button><button className="pp-secondary" onClick={()=>{setDeleting(false);setDeleteText('');}}>Keep profile</button></div>}<p>Need to close your account or remove other records? Use the contact listed in our privacy policy. You can request removal even if you no longer have access to your team.</p></div>}
        </fieldset>
        <footer className="pp-editor-actions">{<label className="pp-terms-check"><input type="checkbox" checked={draft.termsVersion==='2026-09-06'} onChange={e=>update('termsVersion',e.target.checked?'2026-09-06':'')}/> <span>I have permission to upload this content and agree to the <a href="/terms#profile-content" target="_blank" rel="noreferrer">profile content terms</a>. <a href="/privacy#profiles" target="_blank" rel="noreferrer">How TRU uses profile information</a>.</span></label>}{uploading && <p role="status">Preparing your photo…</p>}{discarding ? <><p>Discard your unsaved changes?</p><button className="pp-primary" onClick={() => setDiscarding(false)}>Keep editing</button><button className="pp-secondary" onClick={finishEditing}>Discard changes</button></> : <><span className="pp-help" role="status">{dirty ? 'Unsaved changes' : 'Your preview is up to date'}</span><div><button className="pp-primary" disabled={busy || uploading} onClick={() => void save()}>{busy ? 'Saving…' : 'Save profile'}</button><button className="pp-secondary" disabled={busy || uploading} onClick={() => dirty ? setDiscarding(true) : finishEditing()}>Cancel</button></div></>}</footer>
      </aside>}
    </div>
    <dialog ref={photoDialog} className="pp-photo-dialog" onCancel={()=>setOpenPhoto(null)} onClose={()=>setOpenPhoto(null)}><button autoFocus onClick={()=>setOpenPhoto(null)} aria-label="Close photo">Close ×</button>{openPhoto&&<figure><img src={openPhoto.image} alt={openPhoto.caption||'Personal photo'}/>{openPhoto.caption&&<figcaption>{openPhoto.caption}</figcaption>}</figure>}</dialog>
  </div>;
}
