import {useRef,useState} from 'react';

export const RECORD_TOOLS = [
 {id:'details',label:'Stage & owner',where:'Left column → Details',when:'After the call or event, before you move to another lead.',purpose:'Stage describes what happened. Assigned to identifies the responsible agent. Read Source and Timeframe here too.',example:'Avery agreed to Saturday at 11. Update the stage and save with the green check; also record the agreed meeting in Appointments.',x:1,y:33,w:24,h:28},
 {id:'note',label:'Notes & contact history',where:'Top center → Create Note; history below',when:'Read before outreach; document the outcome immediately afterward.',purpose:'A note preserves context. It does not schedule a reminder. Use the timeline tabs to distinguish calls, personal messages, and earlier notes.',example:'Save the buyer’s request, what was agreed, and what remains unconfirmed. Avoid making the next agent reconstruct the call.',x:26,y:2,w:49,h:55},
 {id:'tasks',label:'Tasks',where:'Right column → Tasks',when:'You or a teammate owe a next action.',purpose:'A dated to-do owned by an agent.',example:'“Call Avery tomorrow at 9:30 to confirm Thursday.” This is work to do, not a booked buyer meeting.',x:75.5,y:5.5,w:24,h:10},
 {id:'appointments',label:'Appointments',where:'Right column → Appointments',when:'A meeting or event has actually been agreed.',purpose:'The scheduled event, with the correct date, time, and people.',example:'“Showing: 406 Juniper, Saturday at 11.” Check for an existing appointment before adding another. “Saturday might work” needs confirmation first.',x:75.5,y:16,w:24,h:10},
 {id:'files',label:'Files',where:'Right column → Files',when:'There is a relevant document to retain under your team’s process.',purpose:'Attachments, not reminders or conversation summaries.',example:'Recognize where an approved document belongs. You do not need to upload a file to complete every call, and a file does not replace the next task.',x:75.5,y:26.5,w:24,h:10},
 {id:'deals',label:'Deals',where:'Right column → Deals',when:'The transaction needs its own record; today we practice an accepted offer.',purpose:'Transaction information such as property, price, and expected closing.',example:'An accepted offer needs the deal details as well as the current contact stage. This does not replace the team’s closing-reporting process.',x:75.5,y:37,w:24,h:10},
 {id:'collaborators',label:'Collaborators',where:'Right column → Collaborators',when:'Another team member needs to help with this contact.',purpose:'Shared access for teamwork, not a task assignment or a buyer’s family relationship.',example:'A covering agent may need access and a dated task. Adding a collaborator alone does not tell them what to do. Follow your team’s access process.',x:75.5,y:47.5,w:24,h:10},
 {id:'automation',label:'Automations & Action Plans',where:'Right column → Automations / Action Plans',when:'Review what the system is doing before sending follow-up.',purpose:'Team-configured workflows. Recognize them; do not build or change them during a new-lead call.',example:'The welcome text may already have gone out. Read it so your next contact makes sense, then make your own outreach. Automation is not your personal attempt.',x:75.5,y:58,w:24,h:20},
 {id:'my-agent',label:'My Agent status',where:'Left column → Details → My Agent status',when:'Check the relationship when reviewing a Zillow contact.',purpose:'Connected identifies an active My Agent relationship. It is separate from the contact’s pipeline stage.',example:'In this image, My Agent is Connected. That does not mean an appointment happened. On your live record, also check expiry and the available Zillow insights.',x:1.5,y:46.5,w:23,h:4},
 {id:'activity',label:'Zillow insights & activity',where:'Right column → lower sidebar',when:'Before outreach, look for useful context about what the buyer is exploring.',purpose:'Current eligible accounts show Zillow Insights with viewed/saved homes and search patterns. This older training image shows Activity in that area.',example:'A saved home can suggest a useful question. It does not establish budget, motivation, or readiness. If Insights is missing, check the My Agent relationship and ask your team lead.',x:75.5,y:79,w:24,h:20},
];

export function RecordMap(){
 const [selected,setSelected]=useState<string|null>(null),[fit,setFit]=useState(false);
 const scroll=useRef<HTMLDivElement>(null);
 const tool=RECORD_TOOLS.find(t=>t.id===selected);
 function choose(id:string){
  setSelected(id);const t=RECORD_TOOLS.find(x=>x.id===id)!;
  if(scroll.current){const el=scroll.current;const width=el.scrollWidth;
   el.scrollTo({left:Math.max(0,width*(t.x+t.w/2)/100-el.clientWidth/2),behavior:'smooth'});}
 }
 return <section className="record-map" aria-label="Explore the contact record">
  <style>{`.record-map{color:#172321;font:16px/1.55 'DM Sans',sans-serif}.record-map-nav{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.record-map-nav button,.record-map-fit{padding:10px 14px;border:1px solid #657e73;border-radius:7px;background:#f4f2ec;color:#172321;cursor:pointer;font:inherit}.record-map-nav button[aria-pressed=true]{background:#25483c;color:#fff}.record-map-help{padding:20px;background:#e4ebe0;border-left:4px solid #527a60;margin:14px 0}.record-map-help h3{margin:0 0 8px}.record-map-help p{margin:7px 0}.record-map-viewport{overflow:auto;border:1px solid #b9c3bd;border-radius:8px}.record-map-image{position:relative;width:1810px;max-width:none}.record-map-image.fit{width:100%;max-width:1810px}.record-map-image img{display:block;width:100%;height:auto;max-width:none}.record-map-hotspot{position:absolute;border:2px solid transparent;background:transparent;cursor:pointer;border-radius:5px}.record-map-hotspot:hover,.record-map-hotspot:focus-visible{border-color:#427858;background:#7fa58c22}.record-map-hotspot[aria-pressed=true]{border:3px solid #427858;box-shadow:0 0 0 3px #fff9}.record-map button:focus-visible{outline:3px solid #285ead;outline-offset:3px}`}</style>
  <p>Select a tool name or its area on the full record. Explore at your own pace; nothing here is graded or saved to Follow Up Boss.</p>
  <div className="record-map-nav">{RECORD_TOOLS.map(t=><button key={t.id} aria-pressed={selected===t.id} onClick={()=>choose(t.id)}>{t.label}</button>)}</div>
  <div className="record-map-help" aria-live="polite">{tool?<><h3>{tool.label} — {tool.where}</h3><p>{tool.purpose}</p><p><strong>When:</strong> {tool.when}</p><p><strong>Example:</strong> {tool.example}</p></>:<p>Start with the area you would use after a buyer asks you to call tomorrow. Then compare it with a confirmed showing.</p>}</div>
  <button className="record-map-fit" aria-pressed={fit} onClick={()=>setFit(v=>!v)}>{fit?'Show full-size record':'Fit the whole record'}</button>
  <div className="record-map-viewport" ref={scroll} tabIndex={0} aria-label="Full contact record; scroll horizontally to inspect">
   <div className={`record-map-image${fit?' fit':''}`}><img src="/rep-lab/detail-full.png" alt="Fictional Follow Up Boss contact with Details on the left, notes in the center, and tools on the right"/>
    {RECORD_TOOLS.map(t=><button key={t.id} className="record-map-hotspot" aria-label={`Explore ${t.label}`} aria-pressed={selected===t.id} onClick={()=>choose(t.id)} style={{left:`${t.x}%`,top:`${t.y}%`,width:`${t.w}%`,height:`${t.h}%`}}/>)}</div>
  </div>
 </section>;
}
