import { useEffect,useState } from 'react';
import { loadDashboard,type AgentRow } from '../lib/api';
import { parseCSV } from '../lib/csv';
import { inPulsePeriod } from '../lib/pulsePeriod';
import { useOperations,type Assignment } from './OperationsContext';
export function AssignmentReview({limit,allowImport=false}:{limit:number;allowImport?:boolean}){
  const ops=useOperations();const [agents,setAgents]=useState<AgentRow[]>([]),[error,setError]=useState(''),[pending,setPending]=useState<Assignment[]|null>(null),[file,setFile]=useState('');
  useEffect(()=>{let active=true;loadDashboard().then(d=>{if(active)setAgents(d.agents);}).catch(()=>{if(active)setError('Agent identity could not be loaded; importing is unavailable.');});return()=>{active=false;};},[]);
  if(!ops)return null;
  const grouped=new Map<string,Assignment[]>();
  for(const r of ops.assignments.filter(r=>inPulsePeriod(r.at,'mtd'))){const list=grouped.get(r.agentId)??[];if(!list.some(x=>x.leadId===r.leadId))list.push(r);grouped.set(r.agentId,list);}
  const flags=[...grouped].filter(([,rows])=>rows.length>=limit);
  return <section className="assignment-review"><h2>Assignment allowance</h2><p>{limit} newly assigned leads per agent · month to date. Imported records count each lead once per agent per month.</p>
    {ops.assignmentFile?<><p>Source: {ops.assignmentFile}. Imported this visit; completeness is not independently verified. Leaving or refreshing clears this import.</p>{flags.map(([id,rows])=><details key={id}><summary>Review pause · {agents.find(a=>a.id===id)?.name||id} · {rows.length}/{limit}</summary><p>Reason: {rows.length} distinct leads assigned this month meet or exceed the saved limit of {limit}.</p>{rows.map(r=><p key={r.leadId}>Lead #{r.leadId} · {new Date(r.at).toLocaleString()} · CSV row {r.line}</p>)}<a href="https://premieragent.zillow.com/leads/routing/routing" target="_blank" rel="noreferrer">Review routing in Zillow ↗</a></details>)}{!flags.length&&<p>No agent reaches the limit in this import. Assignments missing from the file are not included.</p>}
    <details><summary>All imported month-to-date counts</summary>{[...grouped].map(([id,r])=><p key={id}>{agents.find(a=>a.id===id)?.name||id}: {r.length} assigned; {Math.max(0,limit-r.length)} before allowance reached.</p>)}</details></>:<p>We cannot check the limit yet. Assignment dates have not been imported or connected.</p>}
    {allowImport&&<details><summary>Import assignment evidence</summary><p>CSV headers: agent_id, lead_id, assigned_at. Use the agent IDs below and full ISO timestamps with timezone. No upload occurs; the import is held for this signed-in workspace visit only.</p><details><summary>Agent IDs for this workspace</summary>{agents.map(a=><p key={a.id}>{a.name}: {a.id}</p>)}</details>
    <input aria-label="Assignment CSV" type="file" accept=".csv,text/csv" disabled={!agents.length} onChange={async e=>{setPending(null);setError('');const f=e.target.files?.[0];if(!f)return;if(f.size>5000000){setError('Maximum file size is 5 MB.');return;}try{const text=await f.text(),csv=parseCSV(text);if(!csv||!csv.rows.length||(text.match(/"/g)?.length??0)%2)throw Error('CSV is empty or malformed.');const cols=['agent_id','lead_id','assigned_at'].map(k=>csv.headers.indexOf(k));if(cols.some(i=>i<0)||new Set(csv.headers).size!==csv.headers.length)throw Error('Required headers are missing or duplicated.');const rows=csv.rows.map((r,i)=>({agentId:r[cols[0]]?.trim(),leadId:r[cols[1]]?.trim(),at:r[cols[2]]?.trim(),line:i+2}));const bad=rows.find(r=>!agents.some(a=>a.id===r.agentId)||!/^\d+$/.test(r.leadId??'')||!/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(r.at??'')||!Number.isFinite(Date.parse(r.at))||Date.parse(r.at)>Date.now());if(bad)throw Error(`Row ${bad.line}: unknown agent, invalid lead ID or invalid/future timestamp.`);setPending(rows);setFile(f.name);}catch(err){setError(err instanceof Error?err.message:'File could not be read.');}}}/>
    {pending&&<p>{pending.length} valid rows from {file}. <button onClick={()=>{ops.setAssignments(pending,file);setPending(null);}}>Use this assignment evidence</button></p>}</details>}{error&&<p role="alert">{error}</p>}
  </section>;
}
